// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: comment_reactions.sql

package database

import (
	"context"
)

const addCommentReaction = `-- name: AddCommentReaction :one
INSERT INTO comment_reactions (comment_id, user_id, emoji)
VALUES ($1, $2, $3)
ON CONFLICT (comment_id, user_id, emoji)
DO UPDATE SET created_at = CURRENT_TIMESTAMP
RETURNING id, comment_id, user_id, emoji, created_at
`

type AddCommentReactionParams struct {
	CommentID int32
	UserID    int32
	Emoji     string
}

func (q *Queries) AddCommentReaction(ctx context.Context, arg AddCommentReactionParams) (CommentReaction, error) {
	row := q.db.QueryRowContext(ctx, addCommentReaction, arg.CommentID, arg.UserID, arg.Emoji)
	var i CommentReaction
	err := row.Scan(
		&i.ID,
		&i.CommentID,
		&i.UserID,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}

const getCommentReactionsByCommentID = `-- name: GetCommentReactionsByCommentID :many
SELECT emoji, COUNT(*)::int AS count
FROM comment_reactions
WHERE comment_id = $1
GROUP BY emoji
`

type GetCommentReactionsByCommentIDRow struct {
	Emoji string
	Count int32
}

func (q *Queries) GetCommentReactionsByCommentID(ctx context.Context, commentID int32) ([]GetCommentReactionsByCommentIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentReactionsByCommentID, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentReactionsByCommentIDRow
	for rows.Next() {
		var i GetCommentReactionsByCommentIDRow
		if err := rows.Scan(&i.Emoji, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCommentReaction = `-- name: GetUserCommentReaction :one
SELECT id, comment_id, user_id, emoji, created_at FROM comment_reactions
WHERE comment_id = $1 AND user_id = $2 AND emoji = $3
`

type GetUserCommentReactionParams struct {
	CommentID int32
	UserID    int32
	Emoji     string
}

func (q *Queries) GetUserCommentReaction(ctx context.Context, arg GetUserCommentReactionParams) (CommentReaction, error) {
	row := q.db.QueryRowContext(ctx, getUserCommentReaction, arg.CommentID, arg.UserID, arg.Emoji)
	var i CommentReaction
	err := row.Scan(
		&i.ID,
		&i.CommentID,
		&i.UserID,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}

const removeCommentReaction = `-- name: RemoveCommentReaction :exec
DELETE FROM comment_reactions
WHERE comment_id = $1 AND user_id = $2 AND emoji = $3
`

type RemoveCommentReactionParams struct {
	CommentID int32
	UserID    int32
	Emoji     string
}

func (q *Queries) RemoveCommentReaction(ctx context.Context, arg RemoveCommentReactionParams) error {
	_, err := q.db.ExecContext(ctx, removeCommentReaction, arg.CommentID, arg.UserID, arg.Emoji)
	return err
}
