// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: comment_votes.sql

package database

import (
	"context"
)

const deleteCommentVote = `-- name: DeleteCommentVote :exec
DELETE FROM comment_votes WHERE comment_id = $1 AND user_id = $2
`

type DeleteCommentVoteParams struct {
	CommentID int32
	UserID    int32
}

func (q *Queries) DeleteCommentVote(ctx context.Context, arg DeleteCommentVoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteCommentVote, arg.CommentID, arg.UserID)
	return err
}

const getCommentVoteByUser = `-- name: GetCommentVoteByUser :one
SELECT id, comment_id, user_id, vote_type, created_at FROM comment_votes WHERE comment_id = $1 AND user_id = $2
`

type GetCommentVoteByUserParams struct {
	CommentID int32
	UserID    int32
}

func (q *Queries) GetCommentVoteByUser(ctx context.Context, arg GetCommentVoteByUserParams) (CommentVote, error) {
	row := q.db.QueryRowContext(ctx, getCommentVoteByUser, arg.CommentID, arg.UserID)
	var i CommentVote
	err := row.Scan(
		&i.ID,
		&i.CommentID,
		&i.UserID,
		&i.VoteType,
		&i.CreatedAt,
	)
	return i, err
}

const getCommentVoteNetScore = `-- name: GetCommentVoteNetScore :one
SELECT (
    COUNT(*) FILTER (WHERE vote_type = 'upvote') -
    COUNT(*) FILTER (WHERE vote_type = 'downvote')
)::int AS net_score
FROM comment_votes
WHERE comment_id = $1
`

func (q *Queries) GetCommentVoteNetScore(ctx context.Context, commentID int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getCommentVoteNetScore, commentID)
	var net_score int32
	err := row.Scan(&net_score)
	return net_score, err
}

const upsertCommentVote = `-- name: UpsertCommentVote :one
INSERT INTO comment_votes (comment_id, user_id, vote_type)
VALUES ($1, $2, $3)
ON CONFLICT (comment_id, user_id)
DO UPDATE SET vote_type = $3, created_at = CURRENT_TIMESTAMP
RETURNING id, comment_id, user_id, vote_type, created_at
`

type UpsertCommentVoteParams struct {
	CommentID int32
	UserID    int32
	VoteType  string
}

func (q *Queries) UpsertCommentVote(ctx context.Context, arg UpsertCommentVoteParams) (CommentVote, error) {
	row := q.db.QueryRowContext(ctx, upsertCommentVote, arg.CommentID, arg.UserID, arg.VoteType)
	var i CommentVote
	err := row.Scan(
		&i.ID,
		&i.CommentID,
		&i.UserID,
		&i.VoteType,
		&i.CreatedAt,
	)
	return i, err
}
