// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: comment_votes.sql

package database

import (
	"context"

	"github.com/lib/pq"
)

const deleteCommentVote = `-- name: DeleteCommentVote :exec
DELETE FROM comment_votes WHERE comment_id = $1 AND user_id = $2
`

type DeleteCommentVoteParams struct {
	CommentID int32
	UserID    int32
}

func (q *Queries) DeleteCommentVote(ctx context.Context, arg DeleteCommentVoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteCommentVote, arg.CommentID, arg.UserID)
	return err
}

const getCommentVoteByUser = `-- name: GetCommentVoteByUser :one
SELECT id, comment_id, user_id, vote_type, created_at FROM comment_votes WHERE comment_id = $1 AND user_id = $2
`

type GetCommentVoteByUserParams struct {
	CommentID int32
	UserID    int32
}

func (q *Queries) GetCommentVoteByUser(ctx context.Context, arg GetCommentVoteByUserParams) (CommentVotes, error) {
	row := q.db.QueryRowContext(ctx, getCommentVoteByUser, arg.CommentID, arg.UserID)
	var i CommentVotes
	err := row.Scan(
		&i.ID,
		&i.CommentID,
		&i.UserID,
		&i.VoteType,
		&i.CreatedAt,
	)
	return i, err
}

const getCommentVoteNetScore = `-- name: GetCommentVoteNetScore :one
SELECT (
    COUNT(*) FILTER (WHERE vote_type = 'upvote') -
    COUNT(*) FILTER (WHERE vote_type = 'downvote')
)::int AS net_score
FROM comment_votes
WHERE comment_id = $1
`

func (q *Queries) GetCommentVoteNetScore(ctx context.Context, commentID int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getCommentVoteNetScore, commentID)
	var net_score int32
	err := row.Scan(&net_score)
	return net_score, err
}

const getCommentVoteNetScoresBatch = `-- name: GetCommentVoteNetScoresBatch :many
SELECT comment_id,
    (COUNT(*) FILTER (WHERE vote_type = 'upvote') - COUNT(*) FILTER (WHERE vote_type = 'downvote'))::int AS net_score
FROM comment_votes
WHERE comment_id = ANY($1::int[])
GROUP BY comment_id
`

type GetCommentVoteNetScoresBatchRow struct {
	CommentID int32
	NetScore  int32
}

func (q *Queries) GetCommentVoteNetScoresBatch(ctx context.Context, dollar_1 []int32) ([]GetCommentVoteNetScoresBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentVoteNetScoresBatch, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentVoteNetScoresBatchRow
	for rows.Next() {
		var i GetCommentVoteNetScoresBatchRow
		if err := rows.Scan(&i.CommentID, &i.NetScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentVotesByUserForComments = `-- name: GetCommentVotesByUserForComments :many
SELECT comment_id, vote_type
FROM comment_votes
WHERE comment_id = ANY($1::int[]) AND user_id = $2
`

type GetCommentVotesByUserForCommentsParams struct {
	Column1 []int32
	UserID  int32
}

type GetCommentVotesByUserForCommentsRow struct {
	CommentID int32
	VoteType  string
}

func (q *Queries) GetCommentVotesByUserForComments(ctx context.Context, arg GetCommentVotesByUserForCommentsParams) ([]GetCommentVotesByUserForCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentVotesByUserForComments, pq.Array(arg.Column1), arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentVotesByUserForCommentsRow
	for rows.Next() {
		var i GetCommentVotesByUserForCommentsRow
		if err := rows.Scan(&i.CommentID, &i.VoteType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCommentVote = `-- name: UpsertCommentVote :one
INSERT INTO comment_votes (comment_id, user_id, vote_type)
VALUES ($1, $2, $3)
ON CONFLICT (comment_id, user_id)
DO UPDATE SET vote_type = $3, created_at = CURRENT_TIMESTAMP
RETURNING id, comment_id, user_id, vote_type, created_at
`

type UpsertCommentVoteParams struct {
	CommentID int32
	UserID    int32
	VoteType  string
}

func (q *Queries) UpsertCommentVote(ctx context.Context, arg UpsertCommentVoteParams) (CommentVotes, error) {
	row := q.db.QueryRowContext(ctx, upsertCommentVote, arg.CommentID, arg.UserID, arg.VoteType)
	var i CommentVotes
	err := row.Scan(
		&i.ID,
		&i.CommentID,
		&i.UserID,
		&i.VoteType,
		&i.CreatedAt,
	)
	return i, err
}
