// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: content_reports.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createContentReport = `-- name: CreateContentReport :one
INSERT INTO content_reports (
    reporter_id,
    reportable_type,
    reportable_id,
    reason,
    description
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, reporter_id, reportable_type, reportable_id, reason, description, status, created_at
`

type CreateContentReportParams struct {
	ReporterID     int32
	ReportableType string
	ReportableID   uuid.UUID
	Reason         string
	Description    sql.NullString
}

func (q *Queries) CreateContentReport(ctx context.Context, arg CreateContentReportParams) (ContentReports, error) {
	row := q.db.QueryRowContext(ctx, createContentReport,
		arg.ReporterID,
		arg.ReportableType,
		arg.ReportableID,
		arg.Reason,
		arg.Description,
	)
	var i ContentReports
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ReportableType,
		&i.ReportableID,
		&i.Reason,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
