// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: debates.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (debate_id, parent_comment_id, user_id, content, seeded)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, debate_id, parent_comment_id, user_id, content, created_at, updated_at, seeded
`

type CreateCommentParams struct {
	DebateID        sql.NullInt32
	ParentCommentID sql.NullInt32
	UserID          sql.NullInt32
	Content         string
	Seeded          bool
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comments, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.DebateID,
		arg.ParentCommentID,
		arg.UserID,
		arg.Content,
		arg.Seeded,
	)
	var i Comments
	err := row.Scan(
		&i.ID,
		&i.DebateID,
		&i.ParentCommentID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Seeded,
	)
	return i, err
}

const createDebate = `-- name: CreateDebate :one
INSERT INTO debates (match_id, debate_type, headline, description, ai_generated, match_info)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, match_id, debate_type, headline, description, ai_generated, deleted_at, created_at, updated_at, match_info
`

type CreateDebateParams struct {
	MatchID     string
	DebateType  string
	Headline    string
	Description sql.NullString
	AiGenerated sql.NullBool
	MatchInfo   pqtype.NullRawMessage
}

func (q *Queries) CreateDebate(ctx context.Context, arg CreateDebateParams) (Debates, error) {
	row := q.db.QueryRowContext(ctx, createDebate,
		arg.MatchID,
		arg.DebateType,
		arg.Headline,
		arg.Description,
		arg.AiGenerated,
		arg.MatchInfo,
	)
	var i Debates
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.DebateType,
		&i.Headline,
		&i.Description,
		&i.AiGenerated,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchInfo,
	)
	return i, err
}

const createDebateAnalytics = `-- name: CreateDebateAnalytics :one
INSERT INTO debate_analytics (debate_id, total_votes, total_comments, engagement_score)
VALUES ($1, $2, $3, $4)
ON CONFLICT (debate_id) 
DO UPDATE SET 
    total_votes = $2,
    total_comments = $3,
    engagement_score = $4,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, debate_id, total_votes, total_comments, engagement_score, created_at, updated_at
`

type CreateDebateAnalyticsParams struct {
	DebateID        sql.NullInt32
	TotalVotes      sql.NullInt32
	TotalComments   sql.NullInt32
	EngagementScore sql.NullString
}

func (q *Queries) CreateDebateAnalytics(ctx context.Context, arg CreateDebateAnalyticsParams) (DebateAnalytics, error) {
	row := q.db.QueryRowContext(ctx, createDebateAnalytics,
		arg.DebateID,
		arg.TotalVotes,
		arg.TotalComments,
		arg.EngagementScore,
	)
	var i DebateAnalytics
	err := row.Scan(
		&i.ID,
		&i.DebateID,
		&i.TotalVotes,
		&i.TotalComments,
		&i.EngagementScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDebateCard = `-- name: CreateDebateCard :one
INSERT INTO debate_cards (debate_id, stance, title, description, ai_generated)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, debate_id, stance, title, description, ai_generated, created_at, updated_at
`

type CreateDebateCardParams struct {
	DebateID    sql.NullInt32
	Stance      string
	Title       string
	Description sql.NullString
	AiGenerated sql.NullBool
}

func (q *Queries) CreateDebateCard(ctx context.Context, arg CreateDebateCardParams) (DebateCards, error) {
	row := q.db.QueryRowContext(ctx, createDebateCard,
		arg.DebateID,
		arg.Stance,
		arg.Title,
		arg.Description,
		arg.AiGenerated,
	)
	var i DebateCards
	err := row.Scan(
		&i.ID,
		&i.DebateID,
		&i.Stance,
		&i.Title,
		&i.Description,
		&i.AiGenerated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVote = `-- name: CreateVote :one
INSERT INTO votes (debate_card_id, user_id, vote_type, emoji)
VALUES ($1, $2, $3, $4)
ON CONFLICT (debate_card_id, user_id, vote_type, emoji) 
DO UPDATE SET emoji = $4, created_at = CURRENT_TIMESTAMP
RETURNING id, debate_card_id, user_id, vote_type, emoji, created_at
`

type CreateVoteParams struct {
	DebateCardID sql.NullInt32
	UserID       sql.NullInt32
	VoteType     string
	Emoji        sql.NullString
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (Votes, error) {
	row := q.db.QueryRowContext(ctx, createVote,
		arg.DebateCardID,
		arg.UserID,
		arg.VoteType,
		arg.Emoji,
	)
	var i Votes
	err := row.Scan(
		&i.ID,
		&i.DebateCardID,
		&i.UserID,
		&i.VoteType,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCardSwipeVotes = `-- name: DeleteCardSwipeVotes :exec
DELETE FROM votes
WHERE debate_card_id = $1 AND user_id = $2
  AND vote_type IN ('upvote', 'downvote') AND emoji IS NULL
`

type DeleteCardSwipeVotesParams struct {
	DebateCardID sql.NullInt32
	UserID       sql.NullInt32
}

func (q *Queries) DeleteCardSwipeVotes(ctx context.Context, arg DeleteCardSwipeVotesParams) error {
	_, err := q.db.ExecContext(ctx, deleteCardSwipeVotes, arg.DebateCardID, arg.UserID)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const deleteDebate = `-- name: DeleteDebate :exec
DELETE FROM debates WHERE id = $1
`

func (q *Queries) DeleteDebate(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteDebate, id)
	return err
}

const deleteDebateCard = `-- name: DeleteDebateCard :exec
DELETE FROM debate_cards WHERE id = $1
`

func (q *Queries) DeleteDebateCard(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteDebateCard, id)
	return err
}

const deleteVote = `-- name: DeleteVote :exec
DELETE FROM votes WHERE debate_card_id = $1 AND user_id = $2 AND vote_type = $3
`

type DeleteVoteParams struct {
	DebateCardID sql.NullInt32
	UserID       sql.NullInt32
	VoteType     string
}

func (q *Queries) DeleteVote(ctx context.Context, arg DeleteVoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteVote, arg.DebateCardID, arg.UserID, arg.VoteType)
	return err
}

const getComment = `-- name: GetComment :one
SELECT 
    c.id, c.debate_id, c.parent_comment_id, c.user_id, c.content, c.created_at, c.updated_at, c.seeded,
    u.firstname,
    u.lastname,
    u.display_name,
    u.avatar_url
FROM comments c
LEFT JOIN users u ON c.user_id = u.id
WHERE c.id = $1
`

type GetCommentRow struct {
	ID              int32
	DebateID        sql.NullInt32
	ParentCommentID sql.NullInt32
	UserID          sql.NullInt32
	Content         string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	Seeded          bool
	Firstname       sql.NullString
	Lastname        sql.NullString
	DisplayName     sql.NullString
	AvatarUrl       sql.NullString
}

func (q *Queries) GetComment(ctx context.Context, id int32) (GetCommentRow, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i GetCommentRow
	err := row.Scan(
		&i.ID,
		&i.DebateID,
		&i.ParentCommentID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Seeded,
		&i.Firstname,
		&i.Lastname,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return i, err
}

const getCommentCount = `-- name: GetCommentCount :one
SELECT COUNT(*) FROM comments WHERE debate_id = $1
`

func (q *Queries) GetCommentCount(ctx context.Context, debateID sql.NullInt32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCommentCount, debateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getComments = `-- name: GetComments :many
SELECT 
    c.id, c.debate_id, c.parent_comment_id, c.user_id, c.content, c.created_at, c.updated_at, c.seeded,
    u.firstname,
    u.lastname,
    u.display_name,
    u.avatar_url
FROM comments c
LEFT JOIN users u ON c.user_id = u.id
WHERE c.debate_id = $1
ORDER BY c.created_at ASC
`

type GetCommentsRow struct {
	ID              int32
	DebateID        sql.NullInt32
	ParentCommentID sql.NullInt32
	UserID          sql.NullInt32
	Content         string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	Seeded          bool
	Firstname       sql.NullString
	Lastname        sql.NullString
	DisplayName     sql.NullString
	AvatarUrl       sql.NullString
}

func (q *Queries) GetComments(ctx context.Context, debateID sql.NullInt32) ([]GetCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getComments, debateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsRow
	for rows.Next() {
		var i GetCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DebateID,
			&i.ParentCommentID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Seeded,
			&i.Firstname,
			&i.Lastname,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDebate = `-- name: GetDebate :one
SELECT id, match_id, debate_type, headline, description, ai_generated, deleted_at, created_at, updated_at, match_info FROM debates WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDebate(ctx context.Context, id int32) (Debates, error) {
	row := q.db.QueryRowContext(ctx, getDebate, id)
	var i Debates
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.DebateType,
		&i.Headline,
		&i.Description,
		&i.AiGenerated,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchInfo,
	)
	return i, err
}

const getDebateAnalytics = `-- name: GetDebateAnalytics :one
SELECT id, debate_id, total_votes, total_comments, engagement_score, created_at, updated_at FROM debate_analytics WHERE debate_id = $1
`

func (q *Queries) GetDebateAnalytics(ctx context.Context, debateID sql.NullInt32) (DebateAnalytics, error) {
	row := q.db.QueryRowContext(ctx, getDebateAnalytics, debateID)
	var i DebateAnalytics
	err := row.Scan(
		&i.ID,
		&i.DebateID,
		&i.TotalVotes,
		&i.TotalComments,
		&i.EngagementScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDebateCard = `-- name: GetDebateCard :one
SELECT id, debate_id, stance, title, description, ai_generated, created_at, updated_at FROM debate_cards WHERE id = $1
`

func (q *Queries) GetDebateCard(ctx context.Context, id int32) (DebateCards, error) {
	row := q.db.QueryRowContext(ctx, getDebateCard, id)
	var i DebateCards
	err := row.Scan(
		&i.ID,
		&i.DebateID,
		&i.Stance,
		&i.Title,
		&i.Description,
		&i.AiGenerated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDebateCards = `-- name: GetDebateCards :many
SELECT id, debate_id, stance, title, description, ai_generated, created_at, updated_at FROM debate_cards WHERE debate_id = $1 ORDER BY stance
`

func (q *Queries) GetDebateCards(ctx context.Context, debateID sql.NullInt32) ([]DebateCards, error) {
	rows, err := q.db.QueryContext(ctx, getDebateCards, debateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DebateCards
	for rows.Next() {
		var i DebateCards
		if err := rows.Scan(
			&i.ID,
			&i.DebateID,
			&i.Stance,
			&i.Title,
			&i.Description,
			&i.AiGenerated,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDebatesByMatch = `-- name: GetDebatesByMatch :many
SELECT id, match_id, debate_type, headline, description, ai_generated, deleted_at, created_at, updated_at, match_info FROM debates 
WHERE match_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetDebatesByMatch(ctx context.Context, matchID string) ([]Debates, error) {
	rows, err := q.db.QueryContext(ctx, getDebatesByMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debates
	for rows.Next() {
		var i Debates
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.DebateType,
			&i.Headline,
			&i.Description,
			&i.AiGenerated,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MatchInfo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDebatesByType = `-- name: GetDebatesByType :many
SELECT id, match_id, debate_type, headline, description, ai_generated, deleted_at, created_at, updated_at, match_info FROM debates 
WHERE debate_type = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetDebatesByType(ctx context.Context, debateType string) ([]Debates, error) {
	rows, err := q.db.QueryContext(ctx, getDebatesByType, debateType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debates
	for rows.Next() {
		var i Debates
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.DebateType,
			&i.Headline,
			&i.Description,
			&i.AiGenerated,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MatchInfo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopDebates = `-- name: GetTopDebates :many
SELECT 
    d.id, d.match_id, d.debate_type, d.headline, d.description, d.ai_generated, d.deleted_at, d.created_at, d.updated_at, d.match_info,
    da.total_votes,
    da.total_comments,
    da.engagement_score
FROM debates d
LEFT JOIN debate_analytics da ON d.id = da.debate_id
WHERE d.deleted_at IS NULL
ORDER BY da.engagement_score DESC NULLS LAST
LIMIT $1
`

type GetTopDebatesRow struct {
	ID              int32
	MatchID         string
	DebateType      string
	Headline        string
	Description     sql.NullString
	AiGenerated     sql.NullBool
	DeletedAt       sql.NullTime
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	MatchInfo       pqtype.NullRawMessage
	TotalVotes      sql.NullInt32
	TotalComments   sql.NullInt32
	EngagementScore sql.NullString
}

func (q *Queries) GetTopDebates(ctx context.Context, limit int32) ([]GetTopDebatesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopDebates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopDebatesRow
	for rows.Next() {
		var i GetTopDebatesRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.DebateType,
			&i.Headline,
			&i.Description,
			&i.AiGenerated,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MatchInfo,
			&i.TotalVotes,
			&i.TotalComments,
			&i.EngagementScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSwipeVotesForCards = `-- name: GetUserSwipeVotesForCards :many
SELECT id, debate_card_id, user_id, vote_type, emoji, created_at
FROM votes
WHERE user_id = $1
  AND debate_card_id = ANY($2::int[])
  AND emoji IS NULL
  AND vote_type IN ('upvote', 'downvote')
`

type GetUserSwipeVotesForCardsParams struct {
	UserID        sql.NullInt32
	DebateCardIds []int32
}

func (q *Queries) GetUserSwipeVotesForCards(ctx context.Context, arg GetUserSwipeVotesForCardsParams) ([]Votes, error) {
	rows, err := q.db.QueryContext(ctx, getUserSwipeVotesForCards, arg.UserID, pq.Array(arg.DebateCardIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Votes
	for rows.Next() {
		var i Votes
		if err := rows.Scan(
			&i.ID,
			&i.DebateCardID,
			&i.UserID,
			&i.VoteType,
			&i.Emoji,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserVote = `-- name: GetUserVote :one
SELECT id, debate_card_id, user_id, vote_type, emoji, created_at FROM votes WHERE debate_card_id = $1 AND user_id = $2 AND vote_type = $3
`

type GetUserVoteParams struct {
	DebateCardID sql.NullInt32
	UserID       sql.NullInt32
	VoteType     string
}

func (q *Queries) GetUserVote(ctx context.Context, arg GetUserVoteParams) (Votes, error) {
	row := q.db.QueryRowContext(ctx, getUserVote, arg.DebateCardID, arg.UserID, arg.VoteType)
	var i Votes
	err := row.Scan(
		&i.ID,
		&i.DebateCardID,
		&i.UserID,
		&i.VoteType,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}

const getVoteCounts = `-- name: GetVoteCounts :many
SELECT 
    debate_card_id,
    vote_type,
    emoji,
    COUNT(*) as count
FROM votes 
WHERE debate_card_id = ANY($1::int[])
GROUP BY debate_card_id, vote_type, emoji
`

type GetVoteCountsRow struct {
	DebateCardID sql.NullInt32
	VoteType     string
	Emoji        sql.NullString
	Count        int64
}

func (q *Queries) GetVoteCounts(ctx context.Context, dollar_1 []int32) ([]GetVoteCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getVoteCounts, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVoteCountsRow
	for rows.Next() {
		var i GetVoteCountsRow
		if err := rows.Scan(
			&i.DebateCardID,
			&i.VoteType,
			&i.Emoji,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVotesByCard = `-- name: GetVotesByCard :many
SELECT id, debate_card_id, user_id, vote_type, emoji, created_at FROM votes WHERE debate_card_id = $1
`

func (q *Queries) GetVotesByCard(ctx context.Context, debateCardID sql.NullInt32) ([]Votes, error) {
	rows, err := q.db.QueryContext(ctx, getVotesByCard, debateCardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Votes
	for rows.Next() {
		var i Votes
		if err := rows.Scan(
			&i.ID,
			&i.DebateCardID,
			&i.UserID,
			&i.VoteType,
			&i.Emoji,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebatesFeedNewForUser = `-- name: ListDebatesFeedNewForUser :many
WITH feed_candidates AS (
    SELECT d.id
    FROM debates d
    LEFT JOIN debate_analytics da ON d.id = da.debate_id
    WHERE d.deleted_at IS NULL
      AND d.created_at >= CURRENT_TIMESTAMP - INTERVAL '6 days'
      AND EXISTS (SELECT 1 FROM debate_cards dc0 WHERE dc0.debate_id = d.id AND dc0.stance IN ('agree', 'disagree'))
      AND NOT EXISTS (
        SELECT 1
        FROM debate_cards dc
        INNER JOIN votes v ON v.debate_card_id = dc.id AND v.user_id = $1
          AND v.vote_type IN ('upvote', 'downvote')
          AND v.emoji IS NULL
        WHERE dc.debate_id = d.id AND dc.stance IN ('agree', 'disagree')
      )
    ORDER BY da.engagement_score DESC NULLS LAST, d.created_at DESC
    LIMIT $2
)
SELECT 
    d.id, d.match_id, d.debate_type, d.headline, d.description, d.ai_generated, d.match_info, d.deleted_at, d.created_at, d.updated_at,
    da.total_votes,
    da.total_comments,
    da.engagement_score,
    COALESCE(bbin.binary_agree_upvotes, 0) AS binary_agree_upvotes,
    COALESCE(bbin.binary_disagree_upvotes, 0) AS binary_disagree_upvotes
FROM debates d
INNER JOIN feed_candidates fc ON fc.id = d.id
LEFT JOIN debate_analytics da ON d.id = da.debate_id
LEFT JOIN (
    SELECT
        dc.debate_id,
        COUNT(*) FILTER (WHERE dc.stance = 'agree' AND v.vote_type = 'upvote')::bigint AS binary_agree_upvotes,
        COUNT(*) FILTER (
          WHERE (dc.stance = 'agree' AND v.vote_type = 'downvote')
             OR (dc.stance = 'disagree' AND v.vote_type IN ('upvote', 'downvote'))
        )::bigint AS binary_disagree_upvotes
    FROM votes v
    INNER JOIN debate_cards dc ON v.debate_card_id = dc.id
    WHERE v.emoji IS NULL
      AND v.vote_type IN ('upvote', 'downvote')
      AND dc.stance IN ('agree', 'disagree')
      AND dc.debate_id IN (SELECT id FROM feed_candidates)
    GROUP BY dc.debate_id
) bbin ON bbin.debate_id = d.id
ORDER BY da.engagement_score DESC NULLS LAST, d.created_at DESC
`

type ListDebatesFeedNewForUserParams struct {
	UserID sql.NullInt32
	Limit  int32
}

type ListDebatesFeedNewForUserRow struct {
	ID                    int32
	MatchID               string
	DebateType            string
	Headline              string
	Description           sql.NullString
	AiGenerated           sql.NullBool
	MatchInfo             pqtype.NullRawMessage
	DeletedAt             sql.NullTime
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
	TotalVotes            sql.NullInt32
	TotalComments         sql.NullInt32
	EngagementScore       sql.NullString
	BinaryAgreeUpvotes    int64
	BinaryDisagreeUpvotes int64
}

// Authenticated feed — "new": user has not cast any swipe vote (upvote/downvote, emoji IS NULL) on a binary card.
// One vote per debate (first swipe on any binary card moves the debate to "voted"). Emoji reactions do not count. Wildcards do not count.
func (q *Queries) ListDebatesFeedNewForUser(ctx context.Context, arg ListDebatesFeedNewForUserParams) ([]ListDebatesFeedNewForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listDebatesFeedNewForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDebatesFeedNewForUserRow
	for rows.Next() {
		var i ListDebatesFeedNewForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.DebateType,
			&i.Headline,
			&i.Description,
			&i.AiGenerated,
			&i.MatchInfo,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalVotes,
			&i.TotalComments,
			&i.EngagementScore,
			&i.BinaryAgreeUpvotes,
			&i.BinaryDisagreeUpvotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebatesFeedVotedForUser = `-- name: ListDebatesFeedVotedForUser :many
WITH feed_candidates AS (
    SELECT d.id, uv.last_voted_at
    FROM debates d
    INNER JOIN (
      SELECT
        dc.debate_id,
        MAX(v.created_at)::timestamptz AS last_voted_at
      FROM votes v
      INNER JOIN debate_cards dc ON v.debate_card_id = dc.id
      WHERE dc.stance IN ('agree', 'disagree')
        AND v.user_id = $1
        AND v.vote_type IN ('upvote', 'downvote')
        AND v.emoji IS NULL
      GROUP BY dc.debate_id
    ) uv ON uv.debate_id = d.id
    LEFT JOIN debate_analytics da ON d.id = da.debate_id
    WHERE d.deleted_at IS NULL
      AND d.created_at >= CURRENT_TIMESTAMP - INTERVAL '6 days'
      AND EXISTS (SELECT 1 FROM debate_cards dc0 WHERE dc0.debate_id = d.id AND dc0.stance IN ('agree', 'disagree'))
    ORDER BY uv.last_voted_at DESC NULLS LAST
    LIMIT $2
)
SELECT 
    d.id, d.match_id, d.debate_type, d.headline, d.description, d.ai_generated, d.match_info, d.deleted_at, d.created_at, d.updated_at,
    da.total_votes,
    da.total_comments,
    da.engagement_score,
    COALESCE(bbin.binary_agree_upvotes, 0) AS binary_agree_upvotes,
    COALESCE(bbin.binary_disagree_upvotes, 0) AS binary_disagree_upvotes,
    fc.last_voted_at
FROM debates d
INNER JOIN feed_candidates fc ON fc.id = d.id
LEFT JOIN debate_analytics da ON d.id = da.debate_id
LEFT JOIN (
    SELECT
        dc.debate_id,
        COUNT(*) FILTER (WHERE dc.stance = 'agree' AND v.vote_type = 'upvote')::bigint AS binary_agree_upvotes,
        COUNT(*) FILTER (
          WHERE (dc.stance = 'agree' AND v.vote_type = 'downvote')
             OR (dc.stance = 'disagree' AND v.vote_type IN ('upvote', 'downvote'))
        )::bigint AS binary_disagree_upvotes
    FROM votes v
    INNER JOIN debate_cards dc ON v.debate_card_id = dc.id
    WHERE v.emoji IS NULL
      AND v.vote_type IN ('upvote', 'downvote')
      AND dc.stance IN ('agree', 'disagree')
      AND dc.debate_id IN (SELECT id FROM feed_candidates)
    GROUP BY dc.debate_id
) bbin ON bbin.debate_id = d.id
ORDER BY last_voted_at DESC NULLS LAST
`

type ListDebatesFeedVotedForUserParams struct {
	UserID sql.NullInt32
	Limit  int32
}

type ListDebatesFeedVotedForUserRow struct {
	ID                    int32
	MatchID               string
	DebateType            string
	Headline              string
	Description           sql.NullString
	AiGenerated           sql.NullBool
	MatchInfo             pqtype.NullRawMessage
	DeletedAt             sql.NullTime
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
	TotalVotes            sql.NullInt32
	TotalComments         sql.NullInt32
	EngagementScore       sql.NullString
	BinaryAgreeUpvotes    int64
	BinaryDisagreeUpvotes int64
	LastVotedAt           time.Time
}

// Authenticated feed — "voted": user has at least one swipe vote (emoji IS NULL) on any agree/disagree card.
func (q *Queries) ListDebatesFeedVotedForUser(ctx context.Context, arg ListDebatesFeedVotedForUserParams) ([]ListDebatesFeedVotedForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listDebatesFeedVotedForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDebatesFeedVotedForUserRow
	for rows.Next() {
		var i ListDebatesFeedVotedForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.DebateType,
			&i.Headline,
			&i.Description,
			&i.AiGenerated,
			&i.MatchInfo,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalVotes,
			&i.TotalComments,
			&i.EngagementScore,
			&i.BinaryAgreeUpvotes,
			&i.BinaryDisagreeUpvotes,
			&i.LastVotedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebatesPublicFeed = `-- name: ListDebatesPublicFeed :many
WITH feed_candidates AS (
    SELECT d.id
    FROM debates d
    LEFT JOIN debate_analytics da ON d.id = da.debate_id
    WHERE d.deleted_at IS NULL
      AND d.created_at >= CURRENT_TIMESTAMP - INTERVAL '6 days'
      AND EXISTS (SELECT 1 FROM debate_cards dc WHERE dc.debate_id = d.id)
    ORDER BY da.engagement_score DESC NULLS LAST, d.created_at DESC
    LIMIT $1
)
SELECT 
    d.id, d.match_id, d.debate_type, d.headline, d.description, d.ai_generated, d.match_info, d.deleted_at, d.created_at, d.updated_at,
    da.total_votes,
    da.total_comments,
    da.engagement_score,
    COALESCE(bbin.binary_agree_upvotes, 0) AS binary_agree_upvotes,
    COALESCE(bbin.binary_disagree_upvotes, 0) AS binary_disagree_upvotes
FROM debates d
INNER JOIN feed_candidates fc ON fc.id = d.id
LEFT JOIN debate_analytics da ON d.id = da.debate_id
LEFT JOIN (
    SELECT
        dc.debate_id,
        COUNT(*) FILTER (WHERE dc.stance = 'agree' AND v.vote_type = 'upvote')::bigint AS binary_agree_upvotes,
        COUNT(*) FILTER (
          WHERE (dc.stance = 'agree' AND v.vote_type = 'downvote')
             OR (dc.stance = 'disagree' AND v.vote_type IN ('upvote', 'downvote'))
        )::bigint AS binary_disagree_upvotes
    FROM votes v
    INNER JOIN debate_cards dc ON v.debate_card_id = dc.id
    WHERE v.emoji IS NULL
      AND v.vote_type IN ('upvote', 'downvote')
      AND dc.stance IN ('agree', 'disagree')
      AND dc.debate_id IN (SELECT id FROM feed_candidates)
    GROUP BY dc.debate_id
) bbin ON bbin.debate_id = d.id
ORDER BY da.engagement_score DESC NULLS LAST, d.created_at DESC
`

type ListDebatesPublicFeedRow struct {
	ID                    int32
	MatchID               string
	DebateType            string
	Headline              string
	Description           sql.NullString
	AiGenerated           sql.NullBool
	MatchInfo             pqtype.NullRawMessage
	DeletedAt             sql.NullTime
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
	TotalVotes            sql.NullInt32
	TotalComments         sql.NullInt32
	EngagementScore       sql.NullString
	BinaryAgreeUpvotes    int64
	BinaryDisagreeUpvotes int64
}

// Public browse feed: engagement desc, tie-break created_at desc; only debates with at least one card.
// Binary consensus for list UI: agree side = upvotes on agree cards; disagree side = downvotes on agree
// plus all swipe votes on disagree cards (covers detail-screen “no” on agree, hero left as downvote on disagree, legacy upvote-on-disagree).
// Vote aggregates are scoped to debates in the limited feed (not the full votes table).
func (q *Queries) ListDebatesPublicFeed(ctx context.Context, limit int32) ([]ListDebatesPublicFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, listDebatesPublicFeed, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDebatesPublicFeedRow
	for rows.Next() {
		var i ListDebatesPublicFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.DebateType,
			&i.Headline,
			&i.Description,
			&i.AiGenerated,
			&i.MatchInfo,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalVotes,
			&i.TotalComments,
			&i.EngagementScore,
			&i.BinaryAgreeUpvotes,
			&i.BinaryDisagreeUpvotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreDebate = `-- name: RestoreDebate :exec
UPDATE debates SET deleted_at = NULL WHERE id = $1
`

func (q *Queries) RestoreDebate(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, restoreDebate, id)
	return err
}

const softDeleteDebate = `-- name: SoftDeleteDebate :exec
UPDATE debates SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) SoftDeleteDebate(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteDebate, id)
	return err
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments 
SET content = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, debate_id, parent_comment_id, user_id, content, created_at, updated_at, seeded
`

type UpdateCommentParams struct {
	ID      int32
	Content string
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comments, error) {
	row := q.db.QueryRowContext(ctx, updateComment, arg.ID, arg.Content)
	var i Comments
	err := row.Scan(
		&i.ID,
		&i.DebateID,
		&i.ParentCommentID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Seeded,
	)
	return i, err
}

const updateDebate = `-- name: UpdateDebate :one
UPDATE debates 
SET headline = $2, description = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, match_id, debate_type, headline, description, ai_generated, deleted_at, created_at, updated_at, match_info
`

type UpdateDebateParams struct {
	ID          int32
	Headline    string
	Description sql.NullString
}

func (q *Queries) UpdateDebate(ctx context.Context, arg UpdateDebateParams) (Debates, error) {
	row := q.db.QueryRowContext(ctx, updateDebate, arg.ID, arg.Headline, arg.Description)
	var i Debates
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.DebateType,
		&i.Headline,
		&i.Description,
		&i.AiGenerated,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchInfo,
	)
	return i, err
}

const updateDebateAnalytics = `-- name: UpdateDebateAnalytics :one
UPDATE debate_analytics 
SET total_votes = $2, total_comments = $3, engagement_score = $4, updated_at = CURRENT_TIMESTAMP
WHERE debate_id = $1
RETURNING id, debate_id, total_votes, total_comments, engagement_score, created_at, updated_at
`

type UpdateDebateAnalyticsParams struct {
	DebateID        sql.NullInt32
	TotalVotes      sql.NullInt32
	TotalComments   sql.NullInt32
	EngagementScore sql.NullString
}

func (q *Queries) UpdateDebateAnalytics(ctx context.Context, arg UpdateDebateAnalyticsParams) (DebateAnalytics, error) {
	row := q.db.QueryRowContext(ctx, updateDebateAnalytics,
		arg.DebateID,
		arg.TotalVotes,
		arg.TotalComments,
		arg.EngagementScore,
	)
	var i DebateAnalytics
	err := row.Scan(
		&i.ID,
		&i.DebateID,
		&i.TotalVotes,
		&i.TotalComments,
		&i.EngagementScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDebateCard = `-- name: UpdateDebateCard :one
UPDATE debate_cards 
SET title = $2, description = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, debate_id, stance, title, description, ai_generated, created_at, updated_at
`

type UpdateDebateCardParams struct {
	ID          int32
	Title       string
	Description sql.NullString
}

func (q *Queries) UpdateDebateCard(ctx context.Context, arg UpdateDebateCardParams) (DebateCards, error) {
	row := q.db.QueryRowContext(ctx, updateDebateCard, arg.ID, arg.Title, arg.Description)
	var i DebateCards
	err := row.Scan(
		&i.ID,
		&i.DebateID,
		&i.Stance,
		&i.Title,
		&i.Description,
		&i.AiGenerated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
