// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: match_stories.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createMatchStory = `-- name: CreateMatchStory :one
INSERT INTO match_stories (
    user_id,
    scope_type,
    scope_id,
    team_lookup_key,
    content_type,
    media_url,
    caption
) VALUES (
    $1,
    $2::story_scope_type,
    $3,
    $4,
    $5::story_content_type,
    $6,
    $7
)
RETURNING id, user_id, scope_type, scope_id, team_lookup_key, content_type, media_url, caption, is_active, created_at
`

type CreateMatchStoryParams struct {
	UserID        int32
	ScopeType     StoryScopeType
	ScopeID       string
	TeamLookupKey string
	ContentType   StoryContentType
	MediaUrl      string
	Caption       sql.NullString
}

func (q *Queries) CreateMatchStory(ctx context.Context, arg CreateMatchStoryParams) (MatchStories, error) {
	row := q.db.QueryRowContext(ctx, createMatchStory,
		arg.UserID,
		arg.ScopeType,
		arg.ScopeID,
		arg.TeamLookupKey,
		arg.ContentType,
		arg.MediaUrl,
		arg.Caption,
	)
	var i MatchStories
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScopeType,
		&i.ScopeID,
		&i.TeamLookupKey,
		&i.ContentType,
		&i.MediaUrl,
		&i.Caption,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateMatchStory = `-- name: DeactivateMatchStory :one
UPDATE match_stories
SET is_active = FALSE
WHERE id = $1 AND is_active = TRUE
RETURNING id, user_id, scope_type, scope_id, team_lookup_key, content_type, media_url, caption, is_active, created_at
`

func (q *Queries) DeactivateMatchStory(ctx context.Context, id uuid.UUID) (MatchStories, error) {
	row := q.db.QueryRowContext(ctx, deactivateMatchStory, id)
	var i MatchStories
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScopeType,
		&i.ScopeID,
		&i.TeamLookupKey,
		&i.ContentType,
		&i.MediaUrl,
		&i.Caption,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchStoryByID = `-- name: GetMatchStoryByID :one
SELECT id, user_id, scope_type, scope_id, team_lookup_key, content_type, media_url, caption, is_active, created_at FROM match_stories WHERE id = $1
`

func (q *Queries) GetMatchStoryByID(ctx context.Context, id uuid.UUID) (MatchStories, error) {
	row := q.db.QueryRowContext(ctx, getMatchStoryByID, id)
	var i MatchStories
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScopeType,
		&i.ScopeID,
		&i.TeamLookupKey,
		&i.ContentType,
		&i.MediaUrl,
		&i.Caption,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveMatchStoriesForTeam = `-- name: ListActiveMatchStoriesForTeam :many
SELECT
    ms.id, ms.user_id, ms.scope_type, ms.scope_id, ms.team_lookup_key, ms.content_type, ms.media_url, ms.caption, ms.is_active, ms.created_at,
    u.display_name AS user_display_name,
    u.avatar_url AS user_avatar_url
FROM match_stories ms
JOIN users u ON u.id = ms.user_id
WHERE ms.scope_type = $1::story_scope_type
  AND ms.scope_id = $2
  AND ms.team_lookup_key = $3
  AND ms.is_active = TRUE
ORDER BY ms.created_at DESC
LIMIT $4
`

type ListActiveMatchStoriesForTeamParams struct {
	ScopeType     StoryScopeType
	ScopeID       string
	TeamLookupKey string
	RowLimit      int32
}

type ListActiveMatchStoriesForTeamRow struct {
	ID              uuid.UUID
	UserID          int32
	ScopeType       StoryScopeType
	ScopeID         string
	TeamLookupKey   string
	ContentType     StoryContentType
	MediaUrl        string
	Caption         sql.NullString
	IsActive        bool
	CreatedAt       time.Time
	UserDisplayName sql.NullString
	UserAvatarUrl   sql.NullString
}

func (q *Queries) ListActiveMatchStoriesForTeam(ctx context.Context, arg ListActiveMatchStoriesForTeamParams) ([]ListActiveMatchStoriesForTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveMatchStoriesForTeam,
		arg.ScopeType,
		arg.ScopeID,
		arg.TeamLookupKey,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveMatchStoriesForTeamRow
	for rows.Next() {
		var i ListActiveMatchStoriesForTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ScopeType,
			&i.ScopeID,
			&i.TeamLookupKey,
			&i.ContentType,
			&i.MediaUrl,
			&i.Caption,
			&i.IsActive,
			&i.CreatedAt,
			&i.UserDisplayName,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
