// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: me_player_profile.sql

package database

import (
	"context"
	"database/sql"
)

const createMePlayerProfile = `-- name: CreateMePlayerProfile :one
INSERT INTO me_player_profile (user_id, age, country_code, club_name, is_free_agent, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, age, country_code, club_name, is_free_agent, position, photo_url, created_at, updated_at
`

type CreateMePlayerProfileParams struct {
	UserID      int32
	Age         sql.NullInt32
	CountryCode string
	ClubName    sql.NullString
	IsFreeAgent bool
	Position    string
}

func (q *Queries) CreateMePlayerProfile(ctx context.Context, arg CreateMePlayerProfileParams) (MePlayerProfile, error) {
	row := q.db.QueryRowContext(ctx, createMePlayerProfile,
		arg.UserID,
		arg.Age,
		arg.CountryCode,
		arg.ClubName,
		arg.IsFreeAgent,
		arg.Position,
	)
	var i MePlayerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Age,
		&i.CountryCode,
		&i.ClubName,
		&i.IsFreeAgent,
		&i.Position,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMePlayerProfileCareerTeam = `-- name: CreateMePlayerProfileCareerTeam :one
INSERT INTO me_player_profile_career_team (me_player_profile_id, team_name, start_year, end_year)
VALUES ($1, $2, $3, $4)
RETURNING id, me_player_profile_id, team_name, start_year, end_year, created_at, updated_at
`

type CreateMePlayerProfileCareerTeamParams struct {
	MePlayerProfileID int32
	TeamName          string
	StartYear         int32
	EndYear           sql.NullInt32
}

func (q *Queries) CreateMePlayerProfileCareerTeam(ctx context.Context, arg CreateMePlayerProfileCareerTeamParams) (MePlayerProfileCareerTeam, error) {
	row := q.db.QueryRowContext(ctx, createMePlayerProfileCareerTeam,
		arg.MePlayerProfileID,
		arg.TeamName,
		arg.StartYear,
		arg.EndYear,
	)
	var i MePlayerProfileCareerTeam
	err := row.Scan(
		&i.ID,
		&i.MePlayerProfileID,
		&i.TeamName,
		&i.StartYear,
		&i.EndYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMePlayerProfile = `-- name: DeleteMePlayerProfile :exec
DELETE FROM me_player_profile WHERE id = $1
`

func (q *Queries) DeleteMePlayerProfile(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMePlayerProfile, id)
	return err
}

const deleteMePlayerProfileCareerTeam = `-- name: DeleteMePlayerProfileCareerTeam :exec
DELETE FROM me_player_profile_career_team WHERE id = $1
`

func (q *Queries) DeleteMePlayerProfileCareerTeam(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMePlayerProfileCareerTeam, id)
	return err
}

const deleteMePlayerProfileTraitsByProfileID = `-- name: DeleteMePlayerProfileTraitsByProfileID :exec
DELETE FROM me_player_profile_trait WHERE me_player_profile_id = $1
`

func (q *Queries) DeleteMePlayerProfileTraitsByProfileID(ctx context.Context, mePlayerProfileID int32) error {
	_, err := q.db.ExecContext(ctx, deleteMePlayerProfileTraitsByProfileID, mePlayerProfileID)
	return err
}

const getMePlayerProfileByUserID = `-- name: GetMePlayerProfileByUserID :one

SELECT id, user_id, age, country_code, club_name, is_free_agent, position, photo_url, created_at, updated_at FROM me_player_profile WHERE user_id = $1
`

// 007: current user's player profile (me_player_profile), traits, career teams.
func (q *Queries) GetMePlayerProfileByUserID(ctx context.Context, userID int32) (MePlayerProfile, error) {
	row := q.db.QueryRowContext(ctx, getMePlayerProfileByUserID, userID)
	var i MePlayerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Age,
		&i.CountryCode,
		&i.ClubName,
		&i.IsFreeAgent,
		&i.Position,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMePlayerProfileCareerTeam = `-- name: GetMePlayerProfileCareerTeam :one
SELECT id, me_player_profile_id, team_name, start_year, end_year, created_at, updated_at FROM me_player_profile_career_team WHERE id = $1
`

func (q *Queries) GetMePlayerProfileCareerTeam(ctx context.Context, id int32) (MePlayerProfileCareerTeam, error) {
	row := q.db.QueryRowContext(ctx, getMePlayerProfileCareerTeam, id)
	var i MePlayerProfileCareerTeam
	err := row.Scan(
		&i.ID,
		&i.MePlayerProfileID,
		&i.TeamName,
		&i.StartYear,
		&i.EndYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMePlayerProfileTrait = `-- name: InsertMePlayerProfileTrait :one
INSERT INTO me_player_profile_trait (me_player_profile_id, trait_code) VALUES ($1, $2)
RETURNING id, me_player_profile_id, trait_code
`

type InsertMePlayerProfileTraitParams struct {
	MePlayerProfileID int32
	TraitCode         string
}

func (q *Queries) InsertMePlayerProfileTrait(ctx context.Context, arg InsertMePlayerProfileTraitParams) (MePlayerProfileTrait, error) {
	row := q.db.QueryRowContext(ctx, insertMePlayerProfileTrait, arg.MePlayerProfileID, arg.TraitCode)
	var i MePlayerProfileTrait
	err := row.Scan(&i.ID, &i.MePlayerProfileID, &i.TraitCode)
	return i, err
}

const listMePlayerProfileCareerTeams = `-- name: ListMePlayerProfileCareerTeams :many
SELECT id, me_player_profile_id, team_name, start_year, end_year, created_at, updated_at FROM me_player_profile_career_team WHERE me_player_profile_id = $1 ORDER BY start_year DESC
`

func (q *Queries) ListMePlayerProfileCareerTeams(ctx context.Context, mePlayerProfileID int32) ([]MePlayerProfileCareerTeam, error) {
	rows, err := q.db.QueryContext(ctx, listMePlayerProfileCareerTeams, mePlayerProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MePlayerProfileCareerTeam
	for rows.Next() {
		var i MePlayerProfileCareerTeam
		if err := rows.Scan(
			&i.ID,
			&i.MePlayerProfileID,
			&i.TeamName,
			&i.StartYear,
			&i.EndYear,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMePlayerProfileTraits = `-- name: ListMePlayerProfileTraits :many
SELECT trait_code FROM me_player_profile_trait WHERE me_player_profile_id = $1 ORDER BY trait_code
`

func (q *Queries) ListMePlayerProfileTraits(ctx context.Context, mePlayerProfileID int32) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMePlayerProfileTraits, mePlayerProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var trait_code string
		if err := rows.Scan(&trait_code); err != nil {
			return nil, err
		}
		items = append(items, trait_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMePlayerProfile = `-- name: UpdateMePlayerProfile :one
UPDATE me_player_profile
SET age = $2, country_code = $3, club_name = $4, is_free_agent = $5, position = $6, photo_url = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, age, country_code, club_name, is_free_agent, position, photo_url, created_at, updated_at
`

type UpdateMePlayerProfileParams struct {
	ID          int32
	Age         sql.NullInt32
	CountryCode string
	ClubName    sql.NullString
	IsFreeAgent bool
	Position    string
	PhotoUrl    sql.NullString
}

func (q *Queries) UpdateMePlayerProfile(ctx context.Context, arg UpdateMePlayerProfileParams) (MePlayerProfile, error) {
	row := q.db.QueryRowContext(ctx, updateMePlayerProfile,
		arg.ID,
		arg.Age,
		arg.CountryCode,
		arg.ClubName,
		arg.IsFreeAgent,
		arg.Position,
		arg.PhotoUrl,
	)
	var i MePlayerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Age,
		&i.CountryCode,
		&i.ClubName,
		&i.IsFreeAgent,
		&i.Position,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMePlayerProfileCareerTeam = `-- name: UpdateMePlayerProfileCareerTeam :one
UPDATE me_player_profile_career_team
SET team_name = $2, start_year = $3, end_year = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, me_player_profile_id, team_name, start_year, end_year, created_at, updated_at
`

type UpdateMePlayerProfileCareerTeamParams struct {
	ID        int32
	TeamName  string
	StartYear int32
	EndYear   sql.NullInt32
}

func (q *Queries) UpdateMePlayerProfileCareerTeam(ctx context.Context, arg UpdateMePlayerProfileCareerTeamParams) (MePlayerProfileCareerTeam, error) {
	row := q.db.QueryRowContext(ctx, updateMePlayerProfileCareerTeam,
		arg.ID,
		arg.TeamName,
		arg.StartYear,
		arg.EndYear,
	)
	var i MePlayerProfileCareerTeam
	err := row.Scan(
		&i.ID,
		&i.MePlayerProfileID,
		&i.TeamName,
		&i.StartYear,
		&i.EndYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMePlayerProfilePhoto = `-- name: UpdateMePlayerProfilePhoto :one
UPDATE me_player_profile SET photo_url = $2, updated_at = NOW() WHERE id = $1 RETURNING id, user_id, age, country_code, club_name, is_free_agent, position, photo_url, created_at, updated_at
`

type UpdateMePlayerProfilePhotoParams struct {
	ID       int32
	PhotoUrl sql.NullString
}

func (q *Queries) UpdateMePlayerProfilePhoto(ctx context.Context, arg UpdateMePlayerProfilePhotoParams) (MePlayerProfile, error) {
	row := q.db.QueryRowContext(ctx, updateMePlayerProfilePhoto, arg.ID, arg.PhotoUrl)
	var i MePlayerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Age,
		&i.CountryCode,
		&i.ClubName,
		&i.IsFreeAgent,
		&i.Position,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMePlayerProfile = `-- name: UpsertMePlayerProfile :one
INSERT INTO me_player_profile (user_id, age, country_code, club_name, is_free_agent, position)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE SET
  age = EXCLUDED.age,
  country_code = EXCLUDED.country_code,
  club_name = EXCLUDED.club_name,
  is_free_agent = EXCLUDED.is_free_agent,
  position = EXCLUDED.position,
  updated_at = NOW()
RETURNING id, user_id, age, country_code, club_name, is_free_agent, position, photo_url, created_at, updated_at
`

type UpsertMePlayerProfileParams struct {
	UserID      int32
	Age         sql.NullInt32
	CountryCode string
	ClubName    sql.NullString
	IsFreeAgent bool
	Position    string
}

// Atomic create-or-update on user_id (POST /me/player-profile); preserves photo_url on conflict.
func (q *Queries) UpsertMePlayerProfile(ctx context.Context, arg UpsertMePlayerProfileParams) (MePlayerProfile, error) {
	row := q.db.QueryRowContext(ctx, upsertMePlayerProfile,
		arg.UserID,
		arg.Age,
		arg.CountryCode,
		arg.ClubName,
		arg.IsFreeAgent,
		arg.Position,
	)
	var i MePlayerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Age,
		&i.CountryCode,
		&i.ClubName,
		&i.IsFreeAgent,
		&i.Position,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
