// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: media_youtube_channels.sql

package database

import (
	"context"
)

const listActiveMediaYouTubeChannels = `-- name: ListActiveMediaYouTubeChannels :many
SELECT id, lookup_key, display_name, channel_id, channel_handle, sort_order, is_active, is_verified, created_at, updated_at
FROM media_youtube_channels
WHERE is_active = true
ORDER BY sort_order ASC, display_name ASC
`

func (q *Queries) ListActiveMediaYouTubeChannels(ctx context.Context) ([]MediaYoutubeChannels, error) {
	rows, err := q.db.QueryContext(ctx, listActiveMediaYouTubeChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaYoutubeChannels
	for rows.Next() {
		var i MediaYoutubeChannels
		if err := rows.Scan(
			&i.ID,
			&i.LookupKey,
			&i.DisplayName,
			&i.ChannelID,
			&i.ChannelHandle,
			&i.SortOrder,
			&i.IsActive,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
