// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type StoryContentType string

const (
	StoryContentTypePhoto StoryContentType = "photo"
	StoryContentTypeVideo StoryContentType = "video"
)

func (e *StoryContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StoryContentType(s)
	case string:
		*e = StoryContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for StoryContentType: %T", src)
	}
	return nil
}

type NullStoryContentType struct {
	StoryContentType StoryContentType
	Valid            bool // Valid is true if StoryContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStoryContentType) Scan(value interface{}) error {
	if value == nil {
		ns.StoryContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StoryContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStoryContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StoryContentType), nil
}

type StoryScopeType string

const (
	StoryScopeTypeMatch      StoryScopeType = "match"
	StoryScopeTypeTournament StoryScopeType = "tournament"
)

func (e *StoryScopeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StoryScopeType(s)
	case string:
		*e = StoryScopeType(s)
	default:
		return fmt.Errorf("unsupported scan type for StoryScopeType: %T", src)
	}
	return nil
}

type NullStoryScopeType struct {
	StoryScopeType StoryScopeType
	Valid          bool // Valid is true if StoryScopeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStoryScopeType) Scan(value interface{}) error {
	if value == nil {
		ns.StoryScopeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StoryScopeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStoryScopeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StoryScopeType), nil
}

type UserRole string

const (
	UserRoleFan         UserRole = "fan"
	UserRoleTeamManager UserRole = "team_manager"
	UserRoleAdmin       UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type CommentReactions struct {
	ID        int32
	CommentID int32
	UserID    int32
	Emoji     string
	CreatedAt sql.NullTime
}

type CommentVotes struct {
	ID        int32
	CommentID int32
	UserID    int32
	VoteType  string
	CreatedAt sql.NullTime
}

type Comments struct {
	ID              int32
	DebateID        sql.NullInt32
	ParentCommentID sql.NullInt32
	UserID          sql.NullInt32
	Content         string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	Seeded          bool
}

type ContentReports struct {
	ID             uuid.UUID
	ReporterID     int32
	ReportableType string
	ReportableID   string
	Reason         string
	Description    sql.NullString
	Status         string
	CreatedAt      time.Time
	ReportedUserID sql.NullInt32
}

type DebateAnalytics struct {
	ID              int32
	DebateID        sql.NullInt32
	TotalVotes      sql.NullInt32
	TotalComments   sql.NullInt32
	EngagementScore sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type DebateCards struct {
	ID          int32
	DebateID    sql.NullInt32
	Stance      string
	Title       string
	Description sql.NullString
	AiGenerated sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Debates struct {
	ID          int32
	MatchID     string
	DebateType  string
	Headline    string
	Description sql.NullString
	AiGenerated sql.NullBool
	DeletedAt   sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	MatchInfo   pqtype.NullRawMessage
}

type Leagues struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	OwnerID     int32
	Country     sql.NullString
	Level       sql.NullInt32
	LogoUrl     sql.NullString
	Website     sql.NullString
	Founded     sql.NullInt32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MatchStories struct {
	ID            uuid.UUID
	UserID        int32
	ScopeType     StoryScopeType
	ScopeID       string
	TeamLookupKey string
	ContentType   StoryContentType
	MediaUrl      string
	Caption       sql.NullString
	IsActive      bool
	CreatedAt     time.Time
}

type Matches struct {
	ID                uuid.UUID
	ExternalMatchID   string
	HomeTeamID        uuid.NullUUID
	AwayTeamID        uuid.NullUUID
	LeagueID          uuid.NullUUID
	MatchDate         time.Time
	Venue             sql.NullString
	Status            interface{}
	HomeScore         sql.NullInt32
	AwayScore         sql.NullInt32
	MatchMinute       sql.NullInt32
	Referee           sql.NullString
	Attendance        sql.NullInt32
	WeatherConditions sql.NullString
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type Media struct {
	ID        int32
	MatchID   string
	MediaUrl  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MediaYoutubeChannels struct {
	ID            uuid.UUID
	LookupKey     string
	DisplayName   string
	ChannelID     string
	ChannelHandle sql.NullString
	SortOrder     int32
	IsActive      bool
	IsVerified    bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type NationalTeamRankings struct {
	TeamID      int32
	FifaRank    int32
	TeamName    string
	CountryCode sql.NullString
	RankingDate time.Time
	UpdatedAt   time.Time
}

type NewsArticleOpens struct {
	UserID     int32
	ArticleUrl string
	OpenedAt   time.Time
}

type PlayerProfile struct {
	ID          int32
	UserID      int32
	Age         sql.NullInt32
	CountryCode string
	ClubName    sql.NullString
	IsFreeAgent bool
	Position    string
	PhotoUrl    sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Speed       int32
	Shooting    int32
	Passing     int32
	Dribbling   int32
	Defending   int32
	Physical    int32
	Stamina     int32
}

type PlayerProfileCareerTeam struct {
	ID              int32
	PlayerProfileID int32
	TeamName        string
	StartYear       int32
	EndYear         sql.NullInt32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type PlayerProfileTrait struct {
	ID              int32
	PlayerProfileID int32
	TraitCode       string
}

type PushDeliveryLog struct {
	ID           int32
	UserID       int32
	PushDeviceID sql.NullInt32
	CampaignKey  string
	Title        string
	ExpoTicketID sql.NullString
	Status       string
	ErrorMessage sql.NullString
	CreatedAt    time.Time
}

type PushDevices struct {
	ID            int32
	UserID        int32
	ExpoPushToken string
	Platform      string
	Timezone      string
	AppVersion    sql.NullString
	Enabled       bool
	LastSeenAt    time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type PushPreferences struct {
	UserID         int32
	MasterEnabled  bool
	DebatesEnabled bool
	NewsEnabled    bool
	MatchesEnabled bool
	UpdatedAt      time.Time
}

type PushSendLedger struct {
	ID          int32
	UserID      int32
	CampaignKey string
	LocalDate   time.Time
	SentAt      time.Time
}

type TeamManagers struct {
	ID         uuid.UUID
	UserID     int32
	LeagueID   uuid.UUID
	TeamID     uuid.NullUUID
	Title      sql.NullString
	Experience sql.NullInt32
	Bio        sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type TeamYoutubeChannels struct {
	ID            uuid.UUID
	LookupKey     string
	Country       string
	ChannelID     string
	ChannelHandle sql.NullString
	IsActive      bool
	IsVerified    bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Teams struct {
	ID          uuid.UUID
	Name        string
	LeagueID    uuid.NullUUID
	State       sql.NullString
	Country     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description sql.NullString
	ManagerID   uuid.NullUUID
	LogoUrl     sql.NullString
	City        sql.NullString
	Founded     sql.NullInt32
	Stadium     sql.NullString
	Capacity    sql.NullInt32
}

type UserBlocks struct {
	ID            uuid.UUID
	BlockerID     int32
	BlockedUserID int32
	CreatedAt     time.Time
}

type UserFollows struct {
	ID             uuid.UUID
	UserID         int32
	FollowableType interface{}
	FollowableID   uuid.UUID
	CreatedAt      sql.NullTime
}

type Users struct {
	ID                int32
	Firstname         string
	Lastname          string
	Email             string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	IsAdmin           bool
	DisplayName       sql.NullString
	AvatarUrl         sql.NullString
	GoogleID          sql.NullString
	AuthProvider      string
	Locale            sql.NullString
	LastLoginAt       sql.NullTime
	IsVerified        sql.NullBool
	IsActive          sql.NullBool
	Role              NullUserRole
	AppleID           sql.NullString
	AppleRefreshToken sql.NullString `json:"-"`
	TermsAcceptedAt   sql.NullTime
	TermsVersion      sql.NullString
}

type Votes struct {
	ID           int32
	DebateCardID sql.NullInt32
	UserID       sql.NullInt32
	VoteType     string
	Emoji        sql.NullString
	CreatedAt    sql.NullTime
}
