// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type CommentReactions struct {
	ID        int32
	CommentID int32
	UserID    int32
	Emoji     string
	CreatedAt sql.NullTime
}

type CommentVotes struct {
	ID        int32
	CommentID int32
	UserID    int32
	VoteType  string
	CreatedAt sql.NullTime
}

type Comments struct {
	ID              int32
	DebateID        sql.NullInt32
	ParentCommentID sql.NullInt32
	UserID          sql.NullInt32
	Content         string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	Seeded          bool
}

type DebateAnalytics struct {
	ID              int32
	DebateID        sql.NullInt32
	TotalVotes      sql.NullInt32
	TotalComments   sql.NullInt32
	EngagementScore sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type DebateCards struct {
	ID          int32
	DebateID    sql.NullInt32
	Stance      string
	Title       string
	Description sql.NullString
	AiGenerated sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Debates struct {
	ID          int32
	MatchID     string
	DebateType  string
	Headline    string
	Description sql.NullString
	AiGenerated sql.NullBool
	DeletedAt   sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	MatchInfo   pqtype.NullRawMessage
}

type Leagues struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	OwnerID     int32
	Country     sql.NullString
	Level       sql.NullInt32
	LogoUrl     sql.NullString
	Website     sql.NullString
	Founded     sql.NullInt32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Matches struct {
	ID                uuid.UUID
	ExternalMatchID   string
	HomeTeamID        uuid.NullUUID
	AwayTeamID        uuid.NullUUID
	LeagueID          uuid.NullUUID
	MatchDate         time.Time
	Venue             sql.NullString
	Status            interface{}
	HomeScore         sql.NullInt32
	AwayScore         sql.NullInt32
	MatchMinute       sql.NullInt32
	Referee           sql.NullString
	Attendance        sql.NullInt32
	WeatherConditions sql.NullString
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type Media struct {
	ID        int32
	MatchID   string
	MediaUrl  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PlayerProfile struct {
	ID          int32
	UserID      int32
	Age         sql.NullInt32
	CountryCode string
	ClubName    sql.NullString
	IsFreeAgent bool
	Position    string
	PhotoUrl    sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Speed       int32
	Shooting    int32
	Passing     int32
	Dribbling   int32
	Defending   int32
	Physical    int32
	Stamina     int32
}

type PlayerProfileCareerTeam struct {
	ID              int32
	PlayerProfileID int32
	TeamName        string
	StartYear       int32
	EndYear         sql.NullInt32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type PlayerProfileTrait struct {
	ID              int32
	PlayerProfileID int32
	TraitCode       string
}

type TeamManagers struct {
	ID         uuid.UUID
	UserID     int32
	LeagueID   uuid.UUID
	TeamID     uuid.NullUUID
	Title      sql.NullString
	Experience sql.NullInt32
	Bio        sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Teams struct {
	ID          uuid.UUID
	Name        string
	LeagueID    uuid.NullUUID
	State       sql.NullString
	Country     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description sql.NullString
	ManagerID   uuid.NullUUID
	LogoUrl     sql.NullString
	City        sql.NullString
	Founded     sql.NullInt32
	Stadium     sql.NullString
	Capacity    sql.NullInt32
}

type UserFollows struct {
	ID             uuid.UUID
	UserID         int32
	FollowableType interface{}
	FollowableID   uuid.UUID
	CreatedAt      sql.NullTime
}

type Users struct {
	ID           int32
	Firstname    string
	Lastname     string
	Email        string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsAdmin      bool
	DisplayName  sql.NullString
	AvatarUrl    sql.NullString
	GoogleID     sql.NullString
	AuthProvider interface{}
	Locale       sql.NullString
	LastLoginAt  sql.NullTime
}

type Votes struct {
	ID           int32
	DebateCardID sql.NullInt32
	UserID       sql.NullInt32
	VoteType     string
	Emoji        sql.NullString
	CreatedAt    sql.NullTime
}
