// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: national_rankings.sql

package database

import (
	"context"

	"github.com/lib/pq"
)

const getBestFIFARankForTeams = `-- name: GetBestFIFARankForTeams :one
SELECT MIN(fifa_rank)::int AS best_rank
FROM national_team_rankings
WHERE team_id = ANY($1::int[])
`

func (q *Queries) GetBestFIFARankForTeams(ctx context.Context, dollar_1 []int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getBestFIFARankForTeams, pq.Array(dollar_1))
	var best_rank int32
	err := row.Scan(&best_rank)
	return best_rank, err
}

const listNationalTeamRankings = `-- name: ListNationalTeamRankings :many
SELECT team_id, fifa_rank, team_name, country_code, ranking_date, updated_at
FROM national_team_rankings
ORDER BY fifa_rank ASC
`

func (q *Queries) ListNationalTeamRankings(ctx context.Context) ([]NationalTeamRankings, error) {
	rows, err := q.db.QueryContext(ctx, listNationalTeamRankings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NationalTeamRankings
	for rows.Next() {
		var i NationalTeamRankings
		if err := rows.Scan(
			&i.TeamID,
			&i.FifaRank,
			&i.TeamName,
			&i.CountryCode,
			&i.RankingDate,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
