// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: news_opens.sql

package database

import (
	"context"
)

const listOpenedArticleURLsForUser = `-- name: ListOpenedArticleURLsForUser :many
SELECT article_url FROM news_article_opens
WHERE user_id = $1
  AND opened_at >= NOW() - INTERVAL '90 days'
ORDER BY opened_at DESC
LIMIT 500
`

func (q *Queries) ListOpenedArticleURLsForUser(ctx context.Context, userID int32) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listOpenedArticleURLsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var article_url string
		if err := rows.Scan(&article_url); err != nil {
			return nil, err
		}
		items = append(items, article_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNewsArticleOpen = `-- name: UpsertNewsArticleOpen :exec
INSERT INTO news_article_opens (user_id, article_url, opened_at)
VALUES ($1, $2, NOW())
ON CONFLICT (user_id, article_url) DO UPDATE SET opened_at = EXCLUDED.opened_at
`

type UpsertNewsArticleOpenParams struct {
	UserID     int32
	ArticleUrl string
}

func (q *Queries) UpsertNewsArticleOpen(ctx context.Context, arg UpsertNewsArticleOpenParams) error {
	_, err := q.db.ExecContext(ctx, upsertNewsArticleOpen, arg.UserID, arg.ArticleUrl)
	return err
}
