// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: push.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const countPushDevicesForUser = `-- name: CountPushDevicesForUser :one
SELECT COUNT(*)::bigint FROM push_devices
WHERE user_id = $1
`

func (q *Queries) CountPushDevicesForUser(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPushDevicesForUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteOldestPushDeviceForUser = `-- name: DeleteOldestPushDeviceForUser :exec
DELETE FROM push_devices
WHERE id = (
    SELECT pd.id FROM push_devices pd
    WHERE pd.user_id = $1
    ORDER BY pd.last_seen_at ASC
    LIMIT 1
)
`

func (q *Queries) DeleteOldestPushDeviceForUser(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, deleteOldestPushDeviceForUser, userID)
	return err
}

const deletePushDeviceForUser = `-- name: DeletePushDeviceForUser :exec
DELETE FROM push_devices
WHERE id = $1 AND user_id = $2
`

type DeletePushDeviceForUserParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeletePushDeviceForUser(ctx context.Context, arg DeletePushDeviceForUserParams) error {
	_, err := q.db.ExecContext(ctx, deletePushDeviceForUser, arg.ID, arg.UserID)
	return err
}

const disablePushDevice = `-- name: DisablePushDevice :exec
UPDATE push_devices
SET enabled = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DisablePushDevice(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, disablePushDevice, id)
	return err
}

const ensurePushPreferences = `-- name: EnsurePushPreferences :one
INSERT INTO push_preferences (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET updated_at = NOW()
RETURNING user_id, master_enabled, debates_enabled, news_enabled, matches_enabled, updated_at
`

func (q *Queries) EnsurePushPreferences(ctx context.Context, userID int32) (PushPreferences, error) {
	row := q.db.QueryRowContext(ctx, ensurePushPreferences, userID)
	var i PushPreferences
	err := row.Scan(
		&i.UserID,
		&i.MasterEnabled,
		&i.DebatesEnabled,
		&i.NewsEnabled,
		&i.MatchesEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const getPushDeviceByIDForUser = `-- name: GetPushDeviceByIDForUser :one
SELECT id, user_id, expo_push_token, platform, timezone, app_version, enabled, last_seen_at, created_at, updated_at FROM push_devices
WHERE id = $1 AND user_id = $2
`

type GetPushDeviceByIDForUserParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) GetPushDeviceByIDForUser(ctx context.Context, arg GetPushDeviceByIDForUserParams) (PushDevices, error) {
	row := q.db.QueryRowContext(ctx, getPushDeviceByIDForUser, arg.ID, arg.UserID)
	var i PushDevices
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpoPushToken,
		&i.Platform,
		&i.Timezone,
		&i.AppVersion,
		&i.Enabled,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPushPreferences = `-- name: GetPushPreferences :one
SELECT user_id, master_enabled, debates_enabled, news_enabled, matches_enabled, updated_at FROM push_preferences
WHERE user_id = $1
`

func (q *Queries) GetPushPreferences(ctx context.Context, userID int32) (PushPreferences, error) {
	row := q.db.QueryRowContext(ctx, getPushPreferences, userID)
	var i PushPreferences
	err := row.Scan(
		&i.UserID,
		&i.MasterEnabled,
		&i.DebatesEnabled,
		&i.NewsEnabled,
		&i.MatchesEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPushDeliveryLog = `-- name: InsertPushDeliveryLog :one
INSERT INTO push_delivery_log (user_id, push_device_id, campaign_key, title, expo_ticket_id, status, error_message)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, push_device_id, campaign_key, title, expo_ticket_id, status, error_message, created_at
`

type InsertPushDeliveryLogParams struct {
	UserID       int32
	PushDeviceID sql.NullInt32
	CampaignKey  string
	Title        string
	ExpoTicketID sql.NullString
	Status       string
	ErrorMessage sql.NullString
}

func (q *Queries) InsertPushDeliveryLog(ctx context.Context, arg InsertPushDeliveryLogParams) (PushDeliveryLog, error) {
	row := q.db.QueryRowContext(ctx, insertPushDeliveryLog,
		arg.UserID,
		arg.PushDeviceID,
		arg.CampaignKey,
		arg.Title,
		arg.ExpoTicketID,
		arg.Status,
		arg.ErrorMessage,
	)
	var i PushDeliveryLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PushDeviceID,
		&i.CampaignKey,
		&i.Title,
		&i.ExpoTicketID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listEnabledPushDevicesForUser = `-- name: ListEnabledPushDevicesForUser :many
SELECT id, user_id, expo_push_token, platform, timezone, app_version, enabled, last_seen_at, created_at, updated_at FROM push_devices
WHERE user_id = $1 AND enabled = true
ORDER BY last_seen_at DESC
`

func (q *Queries) ListEnabledPushDevicesForUser(ctx context.Context, userID int32) ([]PushDevices, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledPushDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushDevices
	for rows.Next() {
		var i PushDevices
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpoPushToken,
			&i.Platform,
			&i.Timezone,
			&i.AppVersion,
			&i.Enabled,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushDevicesForUser = `-- name: ListPushDevicesForUser :many
SELECT id, user_id, expo_push_token, platform, timezone, app_version, enabled, last_seen_at, created_at, updated_at FROM push_devices
WHERE user_id = $1
ORDER BY last_seen_at DESC
`

func (q *Queries) ListPushDevicesForUser(ctx context.Context, userID int32) ([]PushDevices, error) {
	rows, err := q.db.QueryContext(ctx, listPushDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushDevices
	for rows.Next() {
		var i PushDevices
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpoPushToken,
			&i.Platform,
			&i.Timezone,
			&i.AppVersion,
			&i.Enabled,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryInsertPushSendLedger = `-- name: TryInsertPushSendLedger :one
INSERT INTO push_send_ledger (user_id, campaign_key, local_date)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, campaign_key, local_date) DO NOTHING
RETURNING id, user_id, campaign_key, local_date, sent_at
`

type TryInsertPushSendLedgerParams struct {
	UserID      int32
	CampaignKey string
	LocalDate   time.Time
}

func (q *Queries) TryInsertPushSendLedger(ctx context.Context, arg TryInsertPushSendLedgerParams) (PushSendLedger, error) {
	row := q.db.QueryRowContext(ctx, tryInsertPushSendLedger, arg.UserID, arg.CampaignKey, arg.LocalDate)
	var i PushSendLedger
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CampaignKey,
		&i.LocalDate,
		&i.SentAt,
	)
	return i, err
}

const updatePushPreferences = `-- name: UpdatePushPreferences :one
UPDATE push_preferences
SET
    master_enabled = COALESCE($2, master_enabled),
    debates_enabled = COALESCE($3, debates_enabled),
    news_enabled = COALESCE($4, news_enabled),
    matches_enabled = COALESCE($5, matches_enabled),
    updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, master_enabled, debates_enabled, news_enabled, matches_enabled, updated_at
`

type UpdatePushPreferencesParams struct {
	UserID         int32
	MasterEnabled  sql.NullBool
	DebatesEnabled sql.NullBool
	NewsEnabled    sql.NullBool
	MatchesEnabled sql.NullBool
}

func (q *Queries) UpdatePushPreferences(ctx context.Context, arg UpdatePushPreferencesParams) (PushPreferences, error) {
	row := q.db.QueryRowContext(ctx, updatePushPreferences,
		arg.UserID,
		arg.MasterEnabled,
		arg.DebatesEnabled,
		arg.NewsEnabled,
		arg.MatchesEnabled,
	)
	var i PushPreferences
	err := row.Scan(
		&i.UserID,
		&i.MasterEnabled,
		&i.DebatesEnabled,
		&i.NewsEnabled,
		&i.MatchesEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPushDevice = `-- name: UpsertPushDevice :one
INSERT INTO push_devices (user_id, expo_push_token, platform, timezone, app_version, enabled, last_seen_at, updated_at)
VALUES ($1, $2, $3, $4, $5, true, NOW(), NOW())
ON CONFLICT (expo_push_token) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform,
    timezone = EXCLUDED.timezone,
    app_version = EXCLUDED.app_version,
    enabled = true,
    last_seen_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, expo_push_token, platform, timezone, app_version, enabled, last_seen_at, created_at, updated_at
`

type UpsertPushDeviceParams struct {
	UserID        int32
	ExpoPushToken string
	Platform      string
	Timezone      string
	AppVersion    sql.NullString
}

func (q *Queries) UpsertPushDevice(ctx context.Context, arg UpsertPushDeviceParams) (PushDevices, error) {
	row := q.db.QueryRowContext(ctx, upsertPushDevice,
		arg.UserID,
		arg.ExpoPushToken,
		arg.Platform,
		arg.Timezone,
		arg.AppVersion,
	)
	var i PushDevices
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpoPushToken,
		&i.Platform,
		&i.Timezone,
		&i.AppVersion,
		&i.Enabled,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
