// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: team_youtube_channels.sql

package database

import (
	"context"
)

const getTeamYouTubeChannelByLookupKey = `-- name: GetTeamYouTubeChannelByLookupKey :one
SELECT id, lookup_key, country, channel_id, channel_handle, is_active, is_verified, created_at, updated_at
FROM team_youtube_channels
WHERE lookup_key = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetTeamYouTubeChannelByLookupKey(ctx context.Context, lookupKey string) (TeamYoutubeChannels, error) {
	row := q.db.QueryRowContext(ctx, getTeamYouTubeChannelByLookupKey, lookupKey)
	var i TeamYoutubeChannels
	err := row.Scan(
		&i.ID,
		&i.LookupKey,
		&i.Country,
		&i.ChannelID,
		&i.ChannelHandle,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
