// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const acceptUserTerms = `-- name: AcceptUserTerms :exec
UPDATE users
SET terms_accepted_at = CURRENT_TIMESTAMP,
    terms_version = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type AcceptUserTermsParams struct {
	TermsVersion sql.NullString
	ID           int32
}

func (q *Queries) AcceptUserTerms(ctx context.Context, arg AcceptUserTermsParams) error {
	_, err := q.db.ExecContext(ctx, acceptUserTerms, arg.TermsVersion, arg.ID)
	return err
}

const createAppleUser = `-- name: CreateAppleUser :one
INSERT INTO users (firstname, lastname, email, apple_id, auth_provider, is_admin, is_active, is_verified, last_login_at, apple_refresh_token)
VALUES ($1, $2, $3, $4, 'apple', false, true, true, CURRENT_TIMESTAMP, $5)
RETURNING id, firstname, lastname, email, created_at, updated_at, is_admin, display_name, avatar_url, google_id, auth_provider, locale, last_login_at, is_verified, is_active, role, apple_id, apple_refresh_token, terms_accepted_at, terms_version
`

type CreateAppleUserParams struct {
	Firstname         string
	Lastname          string
	Email             string
	AppleID           sql.NullString
	AppleRefreshToken sql.NullString `json:"-"`
}

func (q *Queries) CreateAppleUser(ctx context.Context, arg CreateAppleUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, createAppleUser,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.AppleID,
		arg.AppleRefreshToken,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.AuthProvider,
		&i.Locale,
		&i.LastLoginAt,
		&i.IsVerified,
		&i.IsActive,
		&i.Role,
		&i.AppleID,
		&i.AppleRefreshToken,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
	)
	return i, err
}

const createGoogleUser = `-- name: CreateGoogleUser :one
INSERT INTO users (firstname, lastname, email, google_id, auth_provider, avatar_url, locale, is_admin, is_active, is_verified, last_login_at)
VALUES ($1, $2, $3, $4, 'google', $5, $6, false, true, true, CURRENT_TIMESTAMP)
RETURNING id, firstname, lastname, email, created_at, updated_at, is_admin, display_name, avatar_url, google_id, auth_provider, locale, last_login_at, is_verified, is_active, role, apple_id, apple_refresh_token, terms_accepted_at, terms_version
`

type CreateGoogleUserParams struct {
	Firstname string
	Lastname  string
	Email     string
	GoogleID  sql.NullString
	AvatarUrl sql.NullString
	Locale    sql.NullString
}

func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, createGoogleUser,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.GoogleID,
		arg.AvatarUrl,
		arg.Locale,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.AuthProvider,
		&i.Locale,
		&i.LastLoginAt,
		&i.IsVerified,
		&i.IsActive,
		&i.Role,
		&i.AppleID,
		&i.AppleRefreshToken,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (firstname, lastname, email, is_admin)
VALUES ($1, $2, $3, $4)
RETURNING id, firstname, lastname, email, created_at, updated_at, is_admin, display_name, avatar_url, google_id, auth_provider, locale, last_login_at, is_verified, is_active, role, apple_id, apple_refresh_token, terms_accepted_at, terms_version
`

type CreateUserParams struct {
	Firstname string
	Lastname  string
	Email     string
	IsAdmin   bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.IsAdmin,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.AuthProvider,
		&i.Locale,
		&i.LastLoginAt,
		&i.IsVerified,
		&i.IsActive,
		&i.Role,
		&i.AppleID,
		&i.AppleRefreshToken,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :one
UPDATE users
SET is_active = FALSE,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, firstname, lastname, email, created_at, updated_at, is_admin, display_name, avatar_url, google_id, auth_provider, locale, last_login_at, is_verified, is_active, role, apple_id, apple_refresh_token, terms_accepted_at, terms_version
`

func (q *Queries) DeactivateUser(ctx context.Context, id int32) (Users, error) {
	row := q.db.QueryRowContext(ctx, deactivateUser, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.AuthProvider,
		&i.Locale,
		&i.LastLoginAt,
		&i.IsVerified,
		&i.IsActive,
		&i.Role,
		&i.AppleID,
		&i.AppleRefreshToken,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, firstname, lastname, email, created_at, updated_at, is_admin, display_name, avatar_url, google_id, auth_provider, locale, last_login_at, is_verified, is_active, role, apple_id, apple_refresh_token, terms_accepted_at, terms_version FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.AuthProvider,
		&i.Locale,
		&i.LastLoginAt,
		&i.IsVerified,
		&i.IsActive,
		&i.Role,
		&i.AppleID,
		&i.AppleRefreshToken,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
	)
	return i, err
}

const getUserByAppleID = `-- name: GetUserByAppleID :one
SELECT id, firstname, lastname, email, created_at, updated_at, is_admin, display_name, avatar_url, google_id, auth_provider, locale, last_login_at, is_verified, is_active, role, apple_id, apple_refresh_token, terms_accepted_at, terms_version FROM users WHERE apple_id = $1::varchar(255)
`

func (q *Queries) GetUserByAppleID(ctx context.Context, appleID string) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUserByAppleID, appleID)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.AuthProvider,
		&i.Locale,
		&i.LastLoginAt,
		&i.IsVerified,
		&i.IsActive,
		&i.Role,
		&i.AppleID,
		&i.AppleRefreshToken,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, firstname, lastname, email, created_at, updated_at, is_admin, display_name, avatar_url, google_id, auth_provider, locale, last_login_at, is_verified, is_active, role, apple_id, apple_refresh_token, terms_accepted_at, terms_version FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.AuthProvider,
		&i.Locale,
		&i.LastLoginAt,
		&i.IsVerified,
		&i.IsActive,
		&i.Role,
		&i.AppleID,
		&i.AppleRefreshToken,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
	)
	return i, err
}

const getUserByEmailLower = `-- name: GetUserByEmailLower :one
SELECT id, firstname, lastname, email, created_at, updated_at, is_admin, display_name, avatar_url, google_id, auth_provider, locale, last_login_at, is_verified, is_active, role, apple_id, apple_refresh_token, terms_accepted_at, terms_version FROM users WHERE email = $1 LIMIT 1
`

// Caller must pass email already lowercased to match stored rows and use a plain index on email.
func (q *Queries) GetUserByEmailLower(ctx context.Context, email string) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailLower, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.AuthProvider,
		&i.Locale,
		&i.LastLoginAt,
		&i.IsVerified,
		&i.IsActive,
		&i.Role,
		&i.AppleID,
		&i.AppleRefreshToken,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, firstname, lastname, email, created_at, updated_at, is_admin, display_name, avatar_url, google_id, auth_provider, locale, last_login_at, is_verified, is_active, role, apple_id, apple_refresh_token, terms_accepted_at, terms_version FROM users WHERE google_id = $1::varchar(255)
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.AuthProvider,
		&i.Locale,
		&i.LastLoginAt,
		&i.IsVerified,
		&i.IsActive,
		&i.Role,
		&i.AppleID,
		&i.AppleRefreshToken,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
	)
	return i, err
}

const isUserActive = `-- name: IsUserActive :one
SELECT COALESCE(is_active, TRUE)::bool AS is_active
FROM users
WHERE id = $1
`

func (q *Queries) IsUserActive(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserActive, id)
	var is_active bool
	err := row.Scan(&is_active)
	return is_active, err
}

const linkAppleToExistingUser = `-- name: LinkAppleToExistingUser :one
UPDATE users
SET apple_id = COALESCE(NULLIF(apple_id::text, ''), $1::text)::varchar(255),
    auth_provider = COALESCE(auth_provider, 'apple'),
    last_login_at = CURRENT_TIMESTAMP,
    apple_refresh_token = COALESCE($2, apple_refresh_token),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, firstname, lastname, email, created_at, updated_at, is_admin, display_name, avatar_url, google_id, auth_provider, locale, last_login_at, is_verified, is_active, role, apple_id, apple_refresh_token, terms_accepted_at, terms_version
`

type LinkAppleToExistingUserParams struct {
	NewAppleID        string
	AppleRefreshToken sql.NullString `json:"-"`
	ID                int32
}

func (q *Queries) LinkAppleToExistingUser(ctx context.Context, arg LinkAppleToExistingUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, linkAppleToExistingUser, arg.NewAppleID, arg.AppleRefreshToken, arg.ID)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.AuthProvider,
		&i.Locale,
		&i.LastLoginAt,
		&i.IsVerified,
		&i.IsActive,
		&i.Role,
		&i.AppleID,
		&i.AppleRefreshToken,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
	)
	return i, err
}

const linkGoogleToExistingUser = `-- name: LinkGoogleToExistingUser :one
UPDATE users
SET google_id = COALESCE(NULLIF(google_id::text, ''), $1::text)::varchar(255),
    auth_provider = COALESCE(auth_provider, 'google'),
    last_login_at = CURRENT_TIMESTAMP,
    avatar_url = CASE WHEN $2::text <> '' THEN $2 ELSE avatar_url END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, firstname, lastname, email, created_at, updated_at, is_admin, display_name, avatar_url, google_id, auth_provider, locale, last_login_at, is_verified, is_active, role, apple_id, apple_refresh_token, terms_accepted_at, terms_version
`

type LinkGoogleToExistingUserParams struct {
	NewGoogleID string
	AvatarUrl   string
	ID          int32
}

func (q *Queries) LinkGoogleToExistingUser(ctx context.Context, arg LinkGoogleToExistingUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, linkGoogleToExistingUser, arg.NewGoogleID, arg.AvatarUrl, arg.ID)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.AuthProvider,
		&i.Locale,
		&i.LastLoginAt,
		&i.IsVerified,
		&i.IsActive,
		&i.Role,
		&i.AppleID,
		&i.AppleRefreshToken,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, firstname, lastname, email, created_at, updated_at, is_admin, display_name, avatar_url, google_id, auth_provider, locale, last_login_at, is_verified, is_active, role, apple_id, apple_refresh_token, terms_accepted_at, terms_version FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]Users, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Users
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.Firstname,
			&i.Lastname,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsAdmin,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.GoogleID,
			&i.AuthProvider,
			&i.Locale,
			&i.LastLoginAt,
			&i.IsVerified,
			&i.IsActive,
			&i.Role,
			&i.AppleID,
			&i.AppleRefreshToken,
			&i.TermsAcceptedAt,
			&i.TermsVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppleLoginFields = `-- name: UpdateAppleLoginFields :one
UPDATE users
SET last_login_at = CURRENT_TIMESTAMP,
    apple_refresh_token = COALESCE($1, apple_refresh_token),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
RETURNING id, firstname, lastname, email, created_at, updated_at, is_admin, display_name, avatar_url, google_id, auth_provider, locale, last_login_at, is_verified, is_active, role, apple_id, apple_refresh_token, terms_accepted_at, terms_version
`

type UpdateAppleLoginFieldsParams struct {
	AppleRefreshToken sql.NullString `json:"-"`
	ID                int32
}

func (q *Queries) UpdateAppleLoginFields(ctx context.Context, arg UpdateAppleLoginFieldsParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, updateAppleLoginFields, arg.AppleRefreshToken, arg.ID)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.AuthProvider,
		&i.Locale,
		&i.LastLoginAt,
		&i.IsVerified,
		&i.IsActive,
		&i.Role,
		&i.AppleID,
		&i.AppleRefreshToken,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
	)
	return i, err
}

const updateGoogleLoginFields = `-- name: UpdateGoogleLoginFields :one
UPDATE users
SET last_login_at = CURRENT_TIMESTAMP,
    avatar_url = CASE WHEN $1::text <> '' THEN $1 ELSE avatar_url END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
RETURNING id, firstname, lastname, email, created_at, updated_at, is_admin, display_name, avatar_url, google_id, auth_provider, locale, last_login_at, is_verified, is_active, role, apple_id, apple_refresh_token, terms_accepted_at, terms_version
`

type UpdateGoogleLoginFieldsParams struct {
	AvatarUrl string
	ID        int32
}

func (q *Queries) UpdateGoogleLoginFields(ctx context.Context, arg UpdateGoogleLoginFieldsParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, updateGoogleLoginFields, arg.AvatarUrl, arg.ID)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.AuthProvider,
		&i.Locale,
		&i.LastLoginAt,
		&i.IsVerified,
		&i.IsActive,
		&i.Role,
		&i.AppleID,
		&i.AppleRefreshToken,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET firstname = $2, lastname = $3, email = $4, is_admin = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, firstname, lastname, email, created_at, updated_at, is_admin, display_name, avatar_url, google_id, auth_provider, locale, last_login_at, is_verified, is_active, role, apple_id, apple_refresh_token, terms_accepted_at, terms_version
`

type UpdateUserParams struct {
	ID        int32
	Firstname string
	Lastname  string
	Email     string
	IsAdmin   bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.IsAdmin,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.AuthProvider,
		&i.Locale,
		&i.LastLoginAt,
		&i.IsVerified,
		&i.IsActive,
		&i.Role,
		&i.AppleID,
		&i.AppleRefreshToken,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
	)
	return i, err
}
