// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user_blocks.sql

package database

import (
	"context"
)

const createUserBlock = `-- name: CreateUserBlock :one
INSERT INTO user_blocks (blocker_id, blocked_user_id)
VALUES ($1, $2)
RETURNING id, blocker_id, blocked_user_id, created_at
`

type CreateUserBlockParams struct {
	BlockerID     int32
	BlockedUserID int32
}

func (q *Queries) CreateUserBlock(ctx context.Context, arg CreateUserBlockParams) (UserBlocks, error) {
	row := q.db.QueryRowContext(ctx, createUserBlock, arg.BlockerID, arg.BlockedUserID)
	var i UserBlocks
	err := row.Scan(
		&i.ID,
		&i.BlockerID,
		&i.BlockedUserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserBlock = `-- name: DeleteUserBlock :exec
DELETE FROM user_blocks
WHERE blocker_id = $1
  AND blocked_user_id = $2
`

type DeleteUserBlockParams struct {
	BlockerID     int32
	BlockedUserID int32
}

func (q *Queries) DeleteUserBlock(ctx context.Context, arg DeleteUserBlockParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserBlock, arg.BlockerID, arg.BlockedUserID)
	return err
}

const getUserBlock = `-- name: GetUserBlock :one
SELECT id, blocker_id, blocked_user_id, created_at FROM user_blocks
WHERE blocker_id = $1
  AND blocked_user_id = $2
`

type GetUserBlockParams struct {
	BlockerID     int32
	BlockedUserID int32
}

func (q *Queries) GetUserBlock(ctx context.Context, arg GetUserBlockParams) (UserBlocks, error) {
	row := q.db.QueryRowContext(ctx, getUserBlock, arg.BlockerID, arg.BlockedUserID)
	var i UserBlocks
	err := row.Scan(
		&i.ID,
		&i.BlockerID,
		&i.BlockedUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listBlockedUserIDs = `-- name: ListBlockedUserIDs :many
SELECT blocked_user_id
FROM user_blocks
WHERE blocker_id = $1
`

func (q *Queries) ListBlockedUserIDs(ctx context.Context, blockerID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, listBlockedUserIDs, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var blocked_user_id int32
		if err := rows.Scan(&blocked_user_id); err != nil {
			return nil, err
		}
		items = append(items, blocked_user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
