# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Update build number
    increment_build_number(xcodeproj: "Fucci.xcodeproj")

    # Build the app
    build_app(
      workspace: "Fucci.xcworkspace",
      scheme: "Fucci",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        provisioningProfiles: { 
          "com.magistridev.fucci" => "Fucci Staging" # This should match your provisioning profile name
        }
      }
    )

    # Upload to TestFlight
    # Note: apple_id here should be the App ID from App Store Connect, not the Apple ID email
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      apple_id: ENV["APPSTORE_APP_ID"], # This should be set to your App Store Connect App ID
      ipa: "./Fucci.ipa"
    )
  end
end
